# Generated by Django 2.2.19 on 2022-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221116_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-03 23:23', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
